//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcapiproyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnoxproyecto
    {
        public int id { get; set; }
        public int id_alumno { get; set; }
        public int id_proyecto { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual proyecto proyecto { get; set; }
    }
}
